name: Export GPG

permissions:
  id-tokens: write
jobs:
  exportgpg:
    runs-on: ubuntu-latest
    steps:
      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY"
          echo "$GPG_PASSPHRASE"

